appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: HKygd4SkYdei+WLRMhNSAe7LFVkvgZV4HuqOBdjy1th7+uq8LrLdq08ZuCssY1ta/s+Y3GIcrJOn3/9PsrsDD+u/8cGnQR45Q8UnnBuDv7k1cgH/K26p+SuHO8hn6/2gX1uScv1CJXccyshZdWez7tMsxP91wYc8pEG0LNKaaF1ZY0xWr+dXKpR71kfiwjiKxleavMc7jQUAXwLV8HM9PuA8IHx+UNSYqpG9gLt+GJimCls6sxOroGFTWePbZmc3h7SFZY7qhXdhUKaSh0eQr90RUiysZrxQTT6TMUGC5p4AYSZVh2nvA7HMhYnVlOmDg6yGaJPFmElsfkaXdt/RB4JVYGIanefE4D032GL06ubCTpif6g7ov/nUqhbmjUt/jbvELHJx9xVeNsDyWcrn/jlIeDzTZVEvNVBu79jNScX4BH5Lgm/G1B9VVbrEz3eA/77HCLgRE1qUSH37M4FfeQOLzq6ffv67KqulpK2kt2zSKQGcgROBNIeunerYE8quwru3En8aqkYVw7SMHZj/BRdRiZxq+MNLZVsLaf0yrmMjoDn1zVJm6KwsVWjmaAmKMZyRXQFkSqW3oKpvKAhLThcCXdcEGeNOc7tslJRfo9P2G/XTFq5UYE1PrkzLba1f3ewUbKVb0NNJTzbVSu1CYVCx+oBcQxV+a82zWOCHSaY=
conda_forge_output_validation: true
